# Generated by Django 5.0.3 on 2024-03-10 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'kategoriya', 'verbose_name_plural': 'kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'mahsulot', 'verbose_name_plural': 'mahsulotlar'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='users',
        ),
    ]
